### ISSUE TITLE
KeyError: 'ExpInt'

### ISSUE THREAD

**Issue by zbli** [AGPeddle/morgawr#1]
After python3 morgawr.py testCtrFile.ctr, I got this:

Traceback (most recent call last):
  File "morgawr.py", line 450, in <module>
    main(sys.argv[1:])
  File "morgawr.py", line 433, in main
    control, state, geometry = initialise(controlFileName)
  File "morgawr.py", line 354, in initialise
    control = Control(controlFileName)
  File "morgawr.py", line 50, in **init**
    super(Control,self).**setitem**('ExpInt',controlData['Control']['ExpInt'])
KeyError: 'ExpInt'

**Comment by AGPeddle** [comment]
I've fixed this by removing the ExpInt option, which was for testing only.
